In [5]:
####numpy array



import numpy as np

a = np.array([1,2,3,4,5])                #array takes list as argument and converts to numpy array

print(a)

print(np.arange(10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
##  %timeit keyword use to calculate time efficiency

a = range(1000)

%timeit [i**2 for i in a]



840 µs ± 138 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
a = np.arange(1000)
##print(type(a))

%timeit a**2

14.2 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
### creatting array manually

a = np.array([0,1,2,3,4,5])                     #vector is one dimensional array

print(type(a))

###areating an array not manually

a = np.arange(6)

print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
## creating 2d array

two_d = np.array([[1,2,3],[1,2,3]])                 #matrix is two dimensional array
print(two_d)
print(len(two_d))
print(np.shape(two_d))
print(two_d.ndim)

[[1 2 3]
 [1 2 3]]
2
(2, 3)
2


In [10]:
### creating 3d array

three_d = np.array( [ [ [1,2,3] , [1,5,3] ] , [ [1,2,3] , [1,2,3] ] ] )

print(three_d)

print(three_d.ndim)

print(three_d.shape)

print(len(three_d))

[[[1 2 3]
  [1 5 3]]

 [[1 2 3]
  [1 2 3]]]
3
(2, 2, 3)
2


In [11]:
###  functions for creating numpy arrays

a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [12]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
a = np.diag([1,2,3,4,5])
print(a)

np.diag (a)           #will extract all the diagonal elements

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([1, 2, 3, 4, 5])

In [13]:
##random numbers

a = np.random.rand(4)                    #uniform random numbers

print(a)

b = np.random.randn(4)                  #standard normalised numbers

print(b)

[0.36186615 0.57383038 0.41823517 0.20430828]
[-1.14924437 -0.30569167  0.38933369  0.01709218]


In [82]:
## basic data types

a = np.array([1,2,3,4],dtype='float64')
a

array([1., 2., 3., 4.])

In [14]:
a = np.array( [ 1+2j , 2+3j ] )

print(a.dtype)
print(a)


complex128
[1.+2.j 2.+3.j]


In [85]:
a = np.array( [True,False,True,False])
a.dtype

dtype('bool')

In [16]:
a = np.array( ["shri",5,"kdjsj","dsjbj"])
print(a.dtype)

<U5


In [17]:
### slicing of numpy array

a = np.array([1,2,3,4,5])

b = a[ : :-1]

b[0]=10
print(a)
print(b)

np.may_share_memory(a,b)                         #tells weather two variables point to same location or not

[ 1  2  3  4 10]
[10  4  3  2  1]


True

In [94]:

a = np.array([1,2,3,4,5])

b = a[ : :-1].copy()

b[0]=10
print(a)
print(b)

np.may_share_memory(a,b)

[1 2 3 4 5]
[10  4  3  2  1]


False

In [103]:
#### fancy indexing

a = np.random.randint(0,20,15)

print(a)
mask = (a%2 == 0)
b = a[mask]
print(b)

[10  2  3  8  9  6 12  4  3 19  4  0 13  8  9]
[10  2  8  6 12  4  4  0  8]


In [106]:
## assigning values through mask

print(a)
a[mask]=-5

print(a)

[-1 -1  3 -1  9 -1 -1 -1  3 19 -1 -1 13 -1  9]
[-5 -5  3 -5  9 -5 -5 -5  3 19 -5 -5 13 -5  9]


In [107]:
#### indexing numpy with integer arrays

c = a[[1,2,3,4]]
c

array([-5,  3, -5,  9])

In [18]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [9]:
sum.__doc__

"Return the sum of a 'start' value (default: 0) plus an iterable of numbers\n\nWhen the iterable is empty, return the start value.\nThis function is intended specifically for use with numeric values and may\nreject non-numeric types."

In [11]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [13]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

