In [2]:
# basic operations on numpy array

import numpy as np

a = np.array([1,2,3,4])

print(a)

a = a+1
print(a)

[1 2 3 4]
[2 3 4 5]


In [16]:
## arithmetic operations on numpy array

b = np.array([5,6,7,8])

c = a+b
print(c)

c = a*b
print(c)

##.dot returns sum of all the elements after multiplication
c=a.dot(b)    
print(c)

[ 7  9 11 13]
[10 18 28 40]
96


In [17]:
c = np.arange(2)
print(c)
print(a)
d= a+c
print(d)                       #in single dimension the vectors can not be broadcasted

[0 1]
[2 3 4 5]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [18]:
### comparison operators
print(a)
print(b)
print(a == b)
print(a>b)
print(a<b)

[2 3 4 5]
[5 6 7 8]
[False False False False]
[False False False False]
[ True  True  True  True]


In [19]:
print(a)
print(b)
print(c)

d = np.array([5,6,7,8])
print(d)
print(np.array_equal(a,b))
print(np.array_equal(b,d))

[2 3 4 5]
[5 6 7 8]
[0 1]
[5 6 7 8]
False
True


In [20]:
### logical operatons

e = np.array([1,0,1,0,1,0],dtype='bool')

f = np.array([1,1,0,1,0,1],dtype='bool')

print(np.logical_or(e,f))


[ True  True  True  True  True  True]


In [21]:
### transcedental functions

print(a)

print(np.sin(a))


print(a)
print(np.log(a))

print(a)
print(np.exp(a))                          ##equivalent to e**a

[2 3 4 5]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[2 3 4 5]
[0.69314718 1.09861229 1.38629436 1.60943791]
[2 3 4 5]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]


In [22]:
#### Basic reduction operations

print(a)
print(a.sum())
print(np.mean(a))
print(np.median(a))
##print(np.stand(a))

[2 3 4 5]
14
3.5
3.5


In [23]:
g = np.array([[1,2],[3,4]])
print(g)
print("**********************")
print(g.sum(axis=0))  
print("**********************")#axis=0 means column wise sum
print(np.sum(g,axis=1))               #axis=1 means row wise sum


[[1 2]
 [3 4]]
**********************
[4 6]
**********************
[3 7]


In [24]:
### other reduction operation 

print(a)
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[2 3 4 5]
2
0
5
3


In [25]:
### logical operations on single array

h = np.array([True,False,True,False])

print(h.all())
print(h.any())

False
True


In [26]:
### statistics operations

i = np.array([1,2,3,4,5,7,9])
j = np.array([[1,2,3],[4,5,6]])
print(i)
print("**********************")
print(j)
print("**********************")
print(i.mean())
print("**********************")
print(j.mean(axis=0))
print("**********************")
print(np.median(j,-1))                                 #-1 and 1 is same for axis
print("**********************")
print(i.std())

[1 2 3 4 5 7 9]
**********************
[[1 2 3]
 [4 5 6]]
**********************
4.428571428571429
**********************
[2.5 3.5 4.5]
**********************
[2. 5.]
**********************
2.610809554642438


#   examples

In [27]:
### load array from population.txt

In [31]:
k = np.loadtxt('populations.txt')                     #load text file into array
k

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [33]:
year,lynx,hare,carrots = k.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [35]:
populations = k[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [36]:
np.mean(lynx)

34080.95238095238

In [37]:
np.mean(hare)

20166.666666666668

In [39]:
np.mean(carrots)

42400.0

# broadcsting

In [61]:
a = np.arange(0,40,10)
b = np.arange(0,4,1)
a = a.reshape((4,1))                    #reshape( may also create a copy)
c = a+b
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [49]:
#### use of tile()

a = np.tile(np.arange(0,40,10),(3,1))
a=a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [52]:
b = np.arange(0,3,1)
b

array([0, 1, 2])

In [53]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [57]:
### to increase dimension of an array
b = np.array([0,1,2])
b = b[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [58]:
#### ravel() converts an n dimension array ot id array

In [60]:
print(b.ravel())


[0 1 2]


In [69]:
##resizing()                      #while resizing it should be taken care that it is not referenced anywhere else

a = np.arange(4)
a.resize((7,))
print(a)

[0 1 2 3 0 0 0]


In [76]:
#### sorting


a = np.array([8,7,6,5,4,3,1,2])
b = np.sort(a)

### inplace sort()
##a.sort()
##a

In [79]:
#### sorting with fancy inexing using argsort()

b = a.argsort()
a[b]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
p = np.arange(0,100,25)
p

array([ 0, 25, 50, 75])